### ISSUE TITLE
Where are the folders located

### ISSUE THREAD

**Issue by vollia** [ilpianista/harbour-Syncthing#1]
Hello, this maybe a noob question , but once the sync of an already existing folder is done I cannot find the corresponding file on the filesystem of my phone.
On the specified location (`/home/defaultuser/Syncthing/Phone` in my case) nothing, but the interface shows the sync as done.

Any idea where the data is located ? A global search on `/` using one of the file syncronised gave nothing.

I am on sailfishos 4.6.0.13, on xperia. Still beginner with sailfish, but ready to help

**Comment by vollia** [comment]
I will have a deeper look, seems related to: https://github.com/sailfishos/sailjail-permissions#sailfish-os-application-sandboxing-and-permissions

**Comment by ilpianista** [comment]
> I will have a deeper look, seems related to: https://github.com/sailfishos/sailjail-permissions#sailfish-os-application-sandboxing-and-permissions

Oh! Thanks for finding this. I use Synthing to only send my files *to* my server, not the viceversa. 

Maybe I could make `Syncthing` a symlink to `~/.local/share/harbour-syncthing/Syncthing` as workaround :thinking:

**Comment by vollia** [comment]
if my understanding is correct, you may add the `UserDirs` permission and it should allow for access to the filesystem.

As far as I am concerned, the `Documents` permission should be enought, but other users may have different usage.

**Comment by ilpianista** [comment]
> if my understanding is correct, you may add the `UserDirs` permission and it should allow for access to the filesystem.

That would only allow access to Documents, Video, Pictures, ... dirs https://github.com/sailfishos/sailjail-permissions/blob/master/permissions/UserDirs.permission

**Comment by vollia** [comment]
That would only allow access to Documents, Video, Pictures, ... dirs https://github.com/sailfishos/sailjail-permissions/blob/master/permissions/UserDirs.permission

You are right. I see see only two way from here:
* either we use a restricted list of folders (either the `.local/share/` only, or some additionaly with the given permission)
* or we disable the sailjail for this app. It seems doable, the file browser does it: [here](https://github.com/ichthyosaurus/harbour-file-browser/blob/main/harbour-file-browser.pro)

I managed to compile the syncthing, unfortunately I am still a beginner in the SFOS world and the 4.5 version used by the emulator does not have the issue. I will continue my work to try to help you here with a more concrete solution.

**Comment by vollia** [comment]
Here is a patch I used successfully:
```patch
diff --git a/harbour-syncthing.desktop b/harbour-syncthing.desktop
index 0b0bc3b..f9be71c 100644
--- a/harbour-syncthing.desktop
+++ b/harbour-syncthing.desktop
@@ -11,3 +11,4 @@ Comment=Continuous Replication Synchronization Thing
 Permissions=Internet;AppLaunch
 OrganizationName=dev.scarpino
 ApplicationName=harbour-syncthing
+Sandboxing=Disabled
```

It corresponds to the second case, which is convenient to put files on my SD card.
See #2 for the corresponding MR.

Best,  
Charles
